### ISSUE TITLE
get_result() error

### ISSUE THREAD

**Issue by silvertriclops** [minicl55/TwitterContest#1]
When I run rt.php I get:
`PHP Fatal error:  Call to undefined method mysqli_stmt::get_result() in /TWIT/rt.php on line 21`
I looked through the code and I can't seem to find where that is, or what replaced it.

**Comment by minicl55** [comment]
Make sure you have mysqlnd installed. `apt-get install php5-mysqlnd` on Debian-based OSs.

**Comment by minicl55** [comment]
If you can't install new packages you can change all the prepared statements to `mysqli_query()`, but this would be insecure as any tweet with SQLi in it could, well, perform SQLi on your database. Probably not a big deal (no important info) but still.
